server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.4:3306/friedkimchi
    username: root
    password: friedkimchi@qwerty

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true